// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gbtznklocfoigwjomrgj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdidHpua2xvY2ZvaWd3am9tcmdqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxNjQxMTIsImV4cCI6MjA2NTc0MDExMn0.YBIYDMeJZ1SBLYa1NCzA8lhliKCWZDE2CrZ34GgASuM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});